collections:
  - name: "course"
    label: "Course"
    folder: "public/content/course"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "course" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }

media_folder: "public/assets/images"
public_folder: "/assets/images"

backend:
  name: github
  repo: "Andhiki/p2mw"
  branch: main
